<a href="https://colab.research.google.com/github/greg881203/Pytorch/blob/main/Practice_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.0+cu118





## Practice

### creating tensor



In [ ]:
tensor = torch.tensor(7)

In [ ]:
tensor.item()

7

In [ ]:
#Vector
vector = torch.tensor([[1,2]])
vector

tensor([[1, 2]])

In [ ]:
vector.ndim 

2

In [ ]:
matrix = torch.tensor([[1,2],[3,4]]) #維度
matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
matrix[0]

tensor([1, 2])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
tensor = torch.tensor([[[1,2,3],
             [4,5,6],
             [7,8,9]]])

In [ ]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Random tensor

In [ ]:
# Create a random tensor of size (3, 4)
ramdom_tensor = torch.rand(3,4)
ramdom_tensor

tensor([[0.1828, 0.4603, 0.2393, 0.3809],
        [0.3881, 0.1290, 0.2081, 0.6029],
        [0.3687, 0.6317, 0.9746, 0.7776]])

In [ ]:
ramdom_tensor.ndim

2

In [ ]:
ramdom_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create a random tensor of size (224, 224, 3)
## For example, say you wanted a random tensor in the common image shape of [224, 224, 3] ([height, width, color_channels]).
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape ,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
ramdom_tensor =torch.rand(3,3,3) 
ramdom_tensor

tensor([[[0.6392, 0.7990, 0.7223],
         [0.3854, 0.1088, 0.3450],
         [0.2718, 0.9244, 0.1707]],

        [[0.0103, 0.6165, 0.8740],
         [0.9612, 0.9918, 0.2086],
         [0.2728, 0.8306, 0.8828]],

        [[0.3768, 0.0136, 0.3268],
         [0.1406, 0.0720, 0.9652],
         [0.2755, 0.7900, 0.9032]]])

##Zero and ones

In [ ]:
# Create a tensor of all zeros
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
ramdom_tensor.dtype

torch.float32

##Creating a range and tensors like

In [ ]:
#Use torch.range()
one_to_ten = torch.arange(1,10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
range = torch.arange(start = 0 , end = 1000 ,step = 77)
range

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tensor datatypes

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [ ]:
mux = float_16_tensor * float_32_tensor
mux.dtype

torch.float32

## Getting information from tensors

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.1636, 0.0669, 0.1852, 0.9170],
        [0.1373, 0.2076, 0.7050, 0.4109],
        [0.6416, 0.0087, 0.8750, 0.7599]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Manipulation Tensors (tensor operations)
Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix Multiplcation



In [ ]:
#Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10 

tensor([10, 20, 30])

In [ ]:
tensor -10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])


### Matrix multiplication

In [ ]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
# value = 0
# tensor1 = [1,2,3]
# for i in range(len(tensor1)):
#   value += tensor1[i] * tensor1[i]
# print(value)

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 9.78 µs


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.11 ms, sys: 5 µs, total: 1.12 ms
Wall time: 1.25 ms


tensor(14)

In [ ]:
torch.matmul(torch.rand(3,10),torch.rand(10,3))

tensor([[3.7077, 2.8639, 2.5777],
        [3.8208, 3.0317, 2.5134],
        [4.0477, 3.0929, 2.6873]])

In [ ]:
torch.matmul(torch.rand(3,10),torch.rand(10,3)).shape

torch.Size([3, 3])

## One of the most common errors in deep learning (shape errors)

In [ ]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
              [3, 4],
              [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
              [8, 11], 
              [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored

In [ ]:
print(tensor_A)
print(tensor_A.shape)
print(tensor_B)
print(tensor_B.shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([3, 2])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])
torch.Size([3, 2])


In [ ]:
tensor_A.T ,tensor_A.T.shape

(tensor([[1., 3., 5.],
         [2., 4., 6.]]),
 torch.Size([2, 3]))

In [ ]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
print(f"Original shapes: tensor_A = {tensor_A.shape},tensor_B = {tensor_B.shape}")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A , tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]),tensor_B = torch.Size([3, 2])
Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


##Finding the min, max, mean, sum, etc (aggregation)

In [132]:
x = torch.arange(0,100,10) 
x 

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [137]:
x.min(),torch.min(x)

(tensor(0), tensor(0))

In [139]:
x.max(),torch.max(x)

(tensor(90), tensor(90))

In [144]:
torch.mean(x.type(torch.float32)) , x.type(torch.float).mean()

(tensor(45.), tensor(45.))

In [147]:
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

In [150]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [155]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

##Positional min/max

In [160]:
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [159]:
#Find the position in tensor 
x.argmin() , x.argmax() ,x[0] , x[9]

(tensor(0), tensor(9), tensor(0), tensor(90))