<a href="https://colab.research.google.com/github/greg881203/Pytorch/blob/main/Practice01_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cu118





## Practice

### creating tensor



In [2]:
tensor = torch.tensor(7)

In [3]:
tensor.item()

7

In [4]:
#Vector
vector = torch.tensor([[1,2]])
vector

tensor([[1, 2]])

In [5]:
vector.ndim 

2

In [6]:
matrix = torch.tensor([[1,2],[3,4]]) #維度
matrix

tensor([[1, 2],
        [3, 4]])

In [7]:
matrix[0]

tensor([1, 2])

In [8]:
matrix.ndim

2

In [9]:
matrix.shape

torch.Size([2, 2])

In [10]:
tensor = torch.tensor([[[1,2,3],
             [4,5,6],
             [7,8,9]]])

In [11]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

In [14]:
tensor[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Random tensor

In [15]:
# Create a random tensor of size (3, 4)
ramdom_tensor = torch.rand(3,4)
ramdom_tensor

tensor([[0.2543, 0.6779, 0.4920, 0.5122],
        [0.0029, 0.0354, 0.6739, 0.7954],
        [0.5489, 0.6558, 0.1017, 0.2108]])

In [16]:
ramdom_tensor.ndim

2

In [17]:
ramdom_tensor.shape

torch.Size([3, 4])

In [18]:
# Create a random tensor of size (224, 224, 3)
## For example, say you wanted a random tensor in the common image shape of [224, 224, 3] ([height, width, color_channels]).
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape ,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
ramdom_tensor =torch.rand(3,3,3) 
ramdom_tensor

tensor([[[0.5301, 0.4115, 0.7765],
         [0.0459, 0.4814, 0.6763],
         [0.0561, 0.7488, 0.4669]],

        [[0.4661, 0.5428, 0.8107],
         [0.5013, 0.6910, 0.7658],
         [0.4888, 0.6463, 0.6468]],

        [[0.4510, 0.8654, 0.0829],
         [0.6902, 0.8818, 0.4184],
         [0.8769, 0.1368, 0.2596]]])

##Zero and ones

In [20]:
# Create a tensor of all zeros
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
ramdom_tensor.dtype

torch.float32

##Creating a range and tensors like

In [24]:
#Use torch.range()
one_to_ten = torch.arange(1,10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
range = torch.arange(start = 0 , end = 1000 ,step = 77)
range

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [26]:
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tensor datatypes

In [27]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [31]:
mux = float_16_tensor * float_32_tensor
mux.dtype

torch.float32

## Getting information from tensors

In [32]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.4527, 0.2898, 0.3223, 0.3102],
        [0.6355, 0.0234, 0.6742, 0.2554],
        [0.7156, 0.7408, 0.2419, 0.6572]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Manipulation Tensors (tensor operations)
Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix Multiplcation



In [33]:
#Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [34]:
tensor * 10 

tensor([10, 20, 30])

In [35]:
tensor -10

tensor([-9, -8, -7])

In [36]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [37]:
torch.add(tensor,10)

tensor([11, 12, 13])


### Matrix multiplication

In [38]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [39]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [40]:
tensor

tensor([1, 2, 3])

In [41]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
# value = 0
# tensor1 = [1,2,3]
# for i in range(len(tensor1)):
#   value += tensor1[i] * tensor1[i]
# print(value)

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 7.63 µs


In [42]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 679 µs, sys: 0 ns, total: 679 µs
Wall time: 586 µs


tensor(14)

In [43]:
torch.matmul(torch.rand(3,10),torch.rand(10,3))

tensor([[3.8380, 3.8597, 3.4022],
        [1.5606, 1.9773, 1.8194],
        [2.3077, 2.6753, 2.0249]])

In [44]:
torch.matmul(torch.rand(3,10),torch.rand(10,3)).shape

torch.Size([3, 3])

## One of the most common errors in deep learning (shape errors)

In [46]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
              [3, 4],
              [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
              [8, 11], 
              [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored

In [47]:
print(tensor_A)
print(tensor_A.shape)
print(tensor_B)
print(tensor_B.shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([3, 2])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])
torch.Size([3, 2])


In [48]:
tensor_A.T ,tensor_A.T.shape

(tensor([[1., 3., 5.],
         [2., 4., 6.]]),
 torch.Size([2, 3]))

In [49]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [50]:
print(f"Original shapes: tensor_A = {tensor_A.shape},tensor_B = {tensor_B.shape}")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A , tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]),tensor_B = torch.Size([3, 2])
Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


##Finding the min, max, mean, sum, etc (aggregation)

In [51]:
x = torch.arange(0,100,10) 
x 

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
x.min(),torch.min(x)

(tensor(0), tensor(0))

In [53]:
x.max(),torch.max(x)

(tensor(90), tensor(90))

In [54]:
torch.mean(x.type(torch.float32)) , x.type(torch.float).mean()

(tensor(45.), tensor(45.))

In [55]:
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

In [56]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [57]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

##Positional min/max

In [58]:
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [59]:
#Find the position in tensor 
x.argmin() , x.argmax() ,x[0] , x[9]

(tensor(0), tensor(9), tensor(0), tensor(90))

##Reshaping, stacking, squeezing and unsqueezing

In [60]:
x = torch.arange(1.,10.)
x ,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [61]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [62]:
# x_reshaped = x.reshape(9,1)
# x_reshaped , x_reshaped.shape

In [63]:
# x_reshaped = x.reshape(3,3)
# x_reshaped , x_reshaped.shape

In [64]:
#Change the view
z = x.view(1,9)
z ,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
# Changing z changes x
z[:,0] = 5
z ,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [66]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [67]:
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [68]:
# torch squeeze 
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [69]:
x_reshaped.shape

torch.Size([1, 9])

In [70]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [71]:
x_reshaped.squeeze().shape

torch.Size([9])

In [72]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [73]:
# torch unsqueeze 

In [74]:
x_reshaped , x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [75]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [76]:
# torch.permute(input, dims)
x_original = torch.rand(size = (224,224,3))#[height , weight, color_channels]
x_original.size()

x_permuted = x_original.permute(2,0,1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [77]:
# x_original[:,:,0].shape
# x_original[0,1,0]

##Indexing (selecting data from tensors)

In [78]:
x= torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [79]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [80]:
x[0][0]

tensor([1, 2, 3])

In [81]:
x[0][0][0]

tensor(1)

In [82]:
x[0][1][1]

tensor(5)

In [83]:
x[0][2][2]

tensor(9)

In [84]:
x[:,0]

tensor([[1, 2, 3]])

In [85]:
x[:,:,1]

tensor([[2, 5, 8]])

In [86]:
x[:,1,1]

tensor([5])

In [87]:
x[0,0,:]

tensor([1, 2, 3])

In [88]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

##PyTorch tensors & NumPy
Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:


torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.

torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

In [89]:
# NumPy array to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float64)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [90]:
array.dtype

dtype('float64')

In [91]:
tensor.dtype

torch.float64

In [92]:
array = array +1 
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [93]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [94]:
tensor = tensor+1
tensor , numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##Reproducibility (trying to take the random out of random)

In [95]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.7509, 0.9301, 0.3863, 0.6489],
        [0.1063, 0.1370, 0.7806, 0.4825],
        [0.0985, 0.1815, 0.1258, 0.9175]])

Tensor B:
tensor([[0.9846, 0.4923, 0.9632, 0.1887],
        [0.9074, 0.3536, 0.6350, 0.9338],
        [0.4734, 0.6375, 0.4344, 0.2511]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [96]:
1==1

True

In [97]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

##1. Getting a GPU

In [98]:
!nvidia-smi


Sat May 20 04:53:27 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

##2. Getting PyTorch to run on the GPU

In [99]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [100]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [101]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

In [103]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [104]:

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [105]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy
tensor_back_on_cpu

<function Tensor.numpy>